# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
 # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install
        
     # - name: Install Heroku CLI
       # run: sudo snap install heroku --classic
        
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
        
      - name: Install Static CLI Plugin
        run: HEROKU_API_KEY=$HEROKU_API_KEY heroku plugins:install heroku-cli-static
        
      - name: Add Heroku remote to local repo
        run: HEROKU_API_KEY=$HEROKU_API_KEY heroku git:remote -a native-global
        
     # - name: Ensure the static buildpack is set
     #   run: HEROKU_API_KEY=$HEROKU_API_KEY heroku buildpacks:set https://github.com/hone/heroku-buildpack-static
        
      - name: Build for web
        run: npm run build
        
      - name: Deploy
        run: HEROKU_API_KEY=$HEROKU_API_KEY heroku static:deploy
